services:
  whiteboard:
    build:
      context: ./whiteboard
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./whiteboard/src:/whiteboard-app/src
    env_file:
      - ./whiteboard/.env
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./postgres/.env
    volumes:
      - ./postgres/volume:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/volume:/data

